# -*- coding: utf-8 -*-
"""OilSpillDetectionMonitoring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GCN7XCI08EkO-f_3DKIqjQiDD5yYBGlZ

**Project Statement:**   
Oil spills pose a serious threat to marine ecosystems, coastal regions, and local economies. Traditional
detection methods such as satellite image manual inspection or physical patrolling are time
consuming, labor-intensive, and often delayed. This project aims to develop an AI-powered oil spill
detection system using machine learning and satellite imagery to identify and localize oil spills
efficiently and accurately. Leveraging deep learning models such as CNNs or U-Net, the system will
analyze satellite images to detect oil spill patterns and generate segmentation maps for real-time
monitoring. This approach helps in early intervention, reducing environmental damage and supporting
emergency response.


**Outcomes**: The goal is to develop an AI-powered system that:

*   Automatically detects and segments oil spills in satellite images
*   Learns visual patterns specific to oil-contaminated regions using deep Learning
*   Produces clear segmentation masks highlighting affected areas
Assists environmental monitoring agencies in rapid oil spill detection and  intervention
*   Is deployable via a user-friendly interface for real-time use

Module 1: Data Collection

• Acquire satellite image datasets such as Sentinel-1 SAR, MODIS, or NOAA.

• Dataset Used: Oil Spill Detection Dataset on Kaggle

• Obtain labeled oil spill annotations from open environmental datasets or manually create custom segmentation masks for training.

• Organize the dataset into a structured format with separate directories for training, validation, and testing.

**NOTE**: Different dataset with pre-seggregated images & masks for Training, Testing and Validation is being used because of dataset size download issues.
"""

#STEP1: Manually download the dataset into PC
#STEP2: Upload to Google Drive
#STEP3: Mount the Google Drive and processing the dataset from Google Drive

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

"""Module 2: Data Exploration and Data Preprocessing

• Visualize sample satellite images and study statistical properties of spill and non-spill regions.

• Resize images to standard dimensions (e.g., 256x256).

• Normalize pixel values and apply SAR-specific filters such as speckle noise reduction.

• Augment dataset through techniques like flipping, rotating, scaling, and
brightness/contrast variation.

"""

# Oil Spill Dataset - Exploration + Preprocessing
# -----------------------------------------------

#Import required Packages
import os, glob, cv2
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

# 1. Dataset paths
# ----------------------------
dataset_path = "/content/drive/MyDrive/Oil_Spill_dataset"

# Training / Validation / Test
train_images = os.path.join(dataset_path, "train/images")
train_masks  = os.path.join(dataset_path, "train/masks")

val_images   = os.path.join(dataset_path, "val/images")
val_masks    = os.path.join(dataset_path, "val/masks")

test_images  = os.path.join(dataset_path, "test/images")
test_masks   = os.path.join(dataset_path, "test/masks")

# Sample check (printing first 5 files, Helps confirm that files are properly loaded.)
print("Train Images (5):", os.listdir(train_images)[:5])
print("Train Masks (5):", os.listdir(train_masks)[:5])

# Collect file paths
train_img_paths = sorted(glob.glob(os.path.join(train_images, "*.jpg")))
train_mask_paths = sorted(glob.glob(os.path.join(train_masks, "*.png")))

val_img_paths = sorted(glob.glob(os.path.join(val_images, "*.jpg")))
val_mask_paths = sorted(glob.glob(os.path.join(val_masks, "*.png")))

test_img_paths = sorted(glob.glob(os.path.join(test_images, "*.jpg")))
test_mask_paths = sorted(glob.glob(os.path.join(test_masks, "*.png")))

print("Train:", len(train_img_paths), "images,", len(train_mask_paths), "masks")  #this checks number of images and masks for all sets
print("Val:", len(val_img_paths), "images,", len(val_mask_paths), "masks")
print("Test:", len(test_img_paths), "images,", len(test_mask_paths), "masks")

#If images and masks match in count. If the dataset is balanced across splits.

import matplotlib.pyplot as plt
import cv2

# Pick first pair
img_path = train_img_paths[0]
mask_path = train_mask_paths[0]

print("Image:", img_path)
print("Mask:", mask_path)

# Read
image = cv2.imread(img_path)
mask = cv2.imread(mask_path, 0)  # grayscale

# Plot
plt.figure(figsize=(10,5))
plt.subplot(1,2,1)
plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
plt.title("Image")

plt.subplot(1,2,2)
plt.imshow(mask, cmap="gray")
plt.title("Mask")
plt.show()

# ----------------------------
# 2. Visualize sample images + masks
# ----------------------------
def show_samples(img_paths, mask_paths, n=3):
    plt.figure(figsize=(12, 6))
    for i in range(n):
        img = cv2.imread(img_paths[i])
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        mask = cv2.imread(mask_paths[i], cv2.IMREAD_GRAYSCALE)

        plt.subplot(2, n, i+1)
        plt.imshow(img)
        plt.title("Satellite Image")
        plt.axis("off")

        plt.subplot(2, n, i+1+n)
        plt.imshow(mask, cmap="gray")
        plt.title("Spill Mask")
        plt.axis("off")
    plt.show()

show_samples(train_img_paths, train_mask_paths, n=3)

# ----------------------------
# 3. Statistical properties
# ----------------------------
def analyze_statistics(img_paths, mask_paths, n=10):
    spill_pixels, nonspill_pixels = [], []

    for i in range(min(n, len(img_paths))):
        img = cv2.imread(img_paths[i], cv2.IMREAD_GRAYSCALE) / 255.0
        mask = cv2.imread(mask_paths[i], cv2.IMREAD_GRAYSCALE)
        mask = (mask > 127).astype(np.uint8)

        spill_pixels.extend(img[mask == 1].flatten())
        nonspill_pixels.extend(img[mask == 0].flatten())

    plt.figure(figsize=(12, 5))
    plt.hist(spill_pixels, bins=50, alpha=0.6, label="Spill Region")
    plt.hist(nonspill_pixels, bins=50, alpha=0.6, label="Non-Spill Region")
    plt.title("Pixel Intensity Distribution")
    plt.xlabel("Normalized Intensity")
    plt.ylabel("Frequency")
    plt.legend()
    plt.show()

analyze_statistics(train_img_paths, train_mask_paths)

'''
You’ll see two distributions:

Spill region intensity distribution.

Non-spill region intensity distribution.

If they are separated, it means the model can easily learn to distinguish oil spills based on pixel brightness.

If they overlap heavily, then you’ll need more advanced features (texture, context, deep CNN) for segmentation.'''

# ----------------------------
# 4. Preprocessing setup
# ----------------------------
IMG_SIZE = (256, 256)
BATCH_SIZE = 8
BUFFER_SIZE = 512
AUTOTUNE = tf.data.AUTOTUNE

# Median filter for speckle noise reduction
def apply_median_filter(img):
    img = img.numpy()
    img = cv2.medianBlur((img*255).astype(np.uint8), 3) #median filter 3x3 median filter is applied..that noised pixel is replaced by the neighbourhood median.
    img = img.astype(np.float32) / 255.0
    return img

def parse_image_mask(img_path, mask_path):
    # Load and decode
    img = tf.io.read_file(img_path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.convert_image_dtype(img, tf.float32)

    mask = tf.io.read_file(mask_path)
    mask = tf.image.decode_png(mask, channels=1)
    mask = tf.image.convert_image_dtype(mask, tf.float32)
    mask = tf.where(mask > 0.5, 1.0, 0.0)  # binarize

    # Resize
    img = tf.image.resize(img, IMG_SIZE, method=tf.image.ResizeMethod.BILINEAR)
    mask = tf.image.resize(mask, IMG_SIZE, method=tf.image.ResizeMethod.NEAREST_NEIGHBOR)

    # Apply SAR noise reduction
    img = tf.py_function(apply_median_filter, [img], tf.float32)

    # Restore shape
    img.set_shape([IMG_SIZE[0], IMG_SIZE[1], 3])
    mask.set_shape([IMG_SIZE[0], IMG_SIZE[1], 1])

    return img, mask

# ----------------------------
# 5. Data augmentation
# ----------------------------
def augment_image_mask(img, mask):
    if tf.random.uniform(()) > 0.5:
        img = tf.image.flip_left_right(img)
        mask = tf.image.flip_left_right(mask)

    if tf.random.uniform(()) > 0.5:
        img = tf.image.flip_up_down(img)
        mask = tf.image.flip_up_down(mask)

    k = tf.random.uniform([], 0, 4, dtype=tf.int32)
    img = tf.image.rot90(img, k)
    mask = tf.image.rot90(mask, k)

    img = tf.image.random_brightness(img, max_delta=0.15)
    img = tf.image.random_contrast(img, lower=0.85, upper=1.15)

    scale = tf.random.uniform([], 0.9, 1.1)
    new_size = (int(IMG_SIZE[0]*scale), int(IMG_SIZE[1]*scale))
    img = tf.image.resize(img, new_size)
    mask = tf.image.resize(mask, new_size, method=tf.image.ResizeMethod.NEAREST_NEIGHBOR)
    img = tf.image.resize_with_crop_or_pad(img, IMG_SIZE[0], IMG_SIZE[1])
    mask = tf.image.resize_with_crop_or_pad(mask, IMG_SIZE[0], IMG_SIZE[1])

    return img, mask

# ----------------------------
# 6. Dataset builder
# ----------------------------
def prepare_dataset(img_paths, mask_paths, training=False):
    ds = tf.data.Dataset.from_tensor_slices((img_paths, mask_paths))
    if training:
        ds = ds.shuffle(BUFFER_SIZE, reshuffle_each_iteration=True)
    ds = ds.map(parse_image_mask, num_parallel_calls=AUTOTUNE)
    if training:
        ds = ds.map(augment_image_mask, num_parallel_calls=AUTOTUNE)
    ds = ds.batch(BATCH_SIZE).prefetch(AUTOTUNE)
    return ds

train_dataset = prepare_dataset(train_img_paths, train_mask_paths, training=True)
val_dataset   = prepare_dataset(val_img_paths, val_mask_paths, training=False)
test_dataset  = prepare_dataset(test_img_paths, test_mask_paths, training=False)

# ----------------------------
# 7. Test visualization of augmentations
# ----------------------------
def show_augmentations(img_path, mask_path, n=3):
    img, mask = parse_image_mask(img_path, mask_path)
    plt.figure(figsize=(12, 4))
    for i in range(n):
        aug_img, aug_mask = augment_image_mask(img, mask)
        plt.subplot(2, n, i+1)
        plt.imshow(aug_img.numpy())
        plt.axis("off")
        plt.title("Augmented Image")

        plt.subplot(2, n, i+1+n)
        plt.imshow(aug_mask.numpy().squeeze(), cmap="gray")
        plt.axis("off")
        plt.title("Augmented Mask")
    plt.show()

show_augmentations(train_img_paths[0], train_mask_paths[0])

import tensorflow as tf
from tensorflow.keras import layers, Model, backend as K

# ---------------------------
# Helper blocks
# ---------------------------
def conv_block(x, filters, kernel_size=3, activation="relu", batchnorm=True):
    x = layers.Conv2D(filters, kernel_size, padding="same", kernel_initializer="he_normal")(x)
    if batchnorm:
        x = layers.BatchNormalization()(x)
    x = layers.Activation(activation)(x)

    x = layers.Conv2D(filters, kernel_size, padding="same", kernel_initializer="he_normal")(x)
    if batchnorm:
        x = layers.BatchNormalization()(x)
    x = layers.Activation(activation)(x)
    return x

def encoder_block(x, filters, pool_size=(2,2), dropout=0.0):
    c = conv_block(x, filters)
    p = layers.MaxPooling2D(pool_size)(c)
    if dropout and dropout > 0:
        p = layers.Dropout(dropout)(p)
    return c, p

def decoder_block(x, skip, filters, kernel_size=3, strides=(2,2)):
    # Use Conv2DTranspose for learned upsampling (alternatively UpSampling2D + Conv)
    x = layers.Conv2DTranspose(filters, kernel_size, strides=strides, padding="same")(x)
    x = layers.Concatenate()([x, skip])
    x = conv_block(x, filters)
    return x

# ---------------------------
# U-Net builder
# ---------------------------
def build_unet(input_shape=(256,256,3), base_filters=32, dropout=0.1):
    inputs = layers.Input(shape=input_shape)

    # Encoder
    c1, p1 = encoder_block(inputs, base_filters)
    c2, p2 = encoder_block(p1, base_filters*2)
    c3, p3 = encoder_block(p2, base_filters*4)
    c4, p4 = encoder_block(p3, base_filters*8)

    # Bottleneck
    bn = conv_block(p4, base_filters*16)
    bn = layers.Dropout(dropout*2)(bn)

    # Decoder
    d4 = decoder_block(bn, c4, base_filters*8)
    d3 = decoder_block(d4, c3, base_filters*4)
    d2 = decoder_block(d3, c2, base_filters*2)
    d1 = decoder_block(d2, c1, base_filters)

    # Output
    outputs = layers.Conv2D(1, (1,1), padding="same", activation="sigmoid")(d1)

    model = Model(inputs, outputs, name="U-Net")
    return model

# ---------------------------
# Losses & metrics
# ---------------------------
def dice_coef(y_true, y_pred, smooth=1e-6):
    y_true_f = K.flatten(y_true)
    y_pred_f = K.flatten(y_pred)
    intersection = K.sum(y_true_f * y_pred_f)
    return (2.0 * intersection + smooth) / (K.sum(y_true_f) + K.sum(y_pred_f) + smooth)

def dice_loss(y_true, y_pred):
    return 1.0 - dice_coef(y_true, y_pred)

def bce_dice_loss(y_true, y_pred):
    bce = tf.keras.losses.BinaryCrossentropy()(y_true, y_pred)
    return bce + dice_loss(y_true, y_pred)

def iou_metric(y_true, y_pred, smooth=1e-6):
    y_pred = K.cast(y_pred > 0.5, 'float32')
    y_true_f = K.flatten(y_true)
    y_pred_f = K.flatten(y_pred)
    intersection = K.sum(y_true_f * y_pred_f)
    union = K.sum(y_true_f) + K.sum(y_pred_f) - intersection
    return (intersection + smooth) / (union + smooth)

# ---------------------------
# Build & compile
# ---------------------------
input_shape = (IMG_SIZE[0], IMG_SIZE[1], 3)  # from your preprocessing
model = build_unet(input_shape=input_shape, base_filters=32, dropout=0.1)
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
              loss=bce_dice_loss,
              metrics=[dice_coef, iou_metric, "accuracy"])

model.summary()

# ---------------------------
# Callbacks (recommended)
# ---------------------------
callbacks = [
    tf.keras.callbacks.ModelCheckpoint("unet_oilspil.h5", save_best_only=True, monitor="val_iou_metric", mode="max"),
    tf.keras.callbacks.EarlyStopping(monitor="val_iou_metric", patience=12, restore_best_weights=True, mode="max"),
    tf.keras.callbacks.ReduceLROnPlateau(monitor="val_iou_metric", factor=0.5, patience=4, min_lr=1e-7, mode="max")
]

# ---------------------------
# Training example
# ---------------------------
EPOCHS = 20
history = model.fit(
    train_dataset,
    validation_data=val_dataset,
    epochs=EPOCHS,
    callbacks=callbacks
)

# After training, evaluate on test set:
test_results = model.evaluate(test_dataset)
print("Test results (loss, dice, iou, acc):", test_results)